set -g base-index 1
set -g pane-base-index 1

set -g renumber-windows on

bind c new-window
bind k kill-pane

bind 1 select-window -t 1
bind 2 select-window -t 2
bind 3 select-window -t 3
bind 4 select-window -t 4
bind 5 select-window -t 5
bind 6 select-window -t 6
bind 7 select-window -t 7
bind 8 select-window -t 8
bind 9 select-window -t 9

set -g mouse on

set-option -g status-position top
set-option -g status-justify centre
set-option -g status-style bg=#18191a,fg=#cdcdcd
set-option -g window-status-current-style bg=#7894ab,fg=#18191a
set-option -g status-right ""
